"use client"
import { FormEvent, useState } from "react"
import { Cpu, Loader2, LockKeyhole } from "lucide-react"

export default function AdminLogin() {
  const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); const response = await fetch("/api/admin/login", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ username, password }) }); setLoading(false); if (!response.ok) { setError("Usuario o contraseña incorrectos."); return }; window.location.href = "/admin" }
  return <main className="flex min-h-screen items-center justify-center bg-background px-5"><section className="w-full max-w-md rounded-3xl border border-border bg-card p-8 shadow-xl"><div className="mb-8 flex items-center gap-3"><div className="flex size-12 items-center justify-center rounded-2xl bg-primary text-primary-foreground"><Cpu className="size-6" /></div><div><p className="font-mono text-xs uppercase tracking-[0.2em] text-primary">RoboLab</p><h1 className="text-2xl font-bold text-primary">Panel administrativo</h1></div></div><form onSubmit={submit} className="flex flex-col gap-5"><label className="flex flex-col gap-2 text-sm font-semibold">Usuario<input required value={username} onChange={(event) => setUsername(event.target.value)} className="h-12 rounded-xl border border-input bg-background px-4 font-normal outline-none focus:border-primary focus:ring-4 focus:ring-ring/20" autoComplete="username" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Contraseña<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="h-12 rounded-xl border border-input bg-background px-4 font-normal outline-none focus:border-primary focus:ring-4 focus:ring-ring/20" autoComplete="current-password" /></label>{error && <p className="text-sm text-destructive">{error}</p>}<button disabled={loading} className="flex h-12 items-center justify-center gap-2 rounded-xl bg-primary font-semibold text-primary-foreground hover:bg-primary/90 disabled:opacity-60">{loading ? <Loader2 className="size-4 animate-spin" /> : <LockKeyhole className="size-4" />}Ingresar</button></form><a href="/" className="mt-6 block text-center text-sm text-muted-foreground hover:text-primary">Volver al quiz</a></section></main>
}
